### ISSUE TITLE
sort not ordering best (exact) matches on top

### ISSUE THREAD

**Issue by arlowhite** [wouter2203/fuzzy-search#32]
I'm using `sort: true`

I have an example where things aren't sorted as expected

search for 'board'
Results in order (searching these two fields):
`'Alarm Dictionary', 'BO_ALARM_DICTIONARY'`
`'Dogmatix Board Replacements', 'DOGMATIX_BOARD_REPLACEMENT_V'`

I would expect the row with "Board" in it to be ordered higher.

But instead, BO_ALARM_DICTIONARY ranks higher, maybe because B O A is close to the beginning of the string?

**Comment by wouter2203** [comment]
It's currently sorting based on the positions of the letters and since BO_ALARM_DICTIONARY has the letters "board" closer to the start of the string it's placing that result higher. 
I agree with you that the way it sorts should be changed so it checks for better matches mid words/sentence. (Like the fuzzy search in sublime)
I'll probably add an extra option to change the sorting mechanic and make this new method the default, but that's something I yet have to decide. 
I'll look into this asap (probably this weekend)!
-------- Oorspronkelijk bericht --------Van: Arlo White <notifications@github.com> Datum: 31-10-17  22:42  (GMT+01:00) Aan: wouter2203/fuzzy-search <fuzzy-search@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [wouter2203/fuzzy-search] sort not ordering best (exact) matches on top (#32) 
I'm using sort: true
I have an example where things aren't sorted as expected
search for 'board'

Results in order (searching these two fields):

'Alarm Dictionary', 'BO_ALARM_DICTIONARY'

'Dogmatix Board Replacements', 'DOGMATIX_BOARD_REPLACEMENT_V'
I would expect the row with "Board" in it to be ordered higher.
But instead, BO_ALARM_DICTIONARY ranks higher, maybe because B O A is close to the beginning of the string?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/wouter2203/fuzzy-search","title":"wouter2203/fuzzy-search","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/wouter2203/fuzzy-search"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"sort not ordering best (exact) matches on top (#32)"}],"action":{"name":"View Issue","url":"https://github.com/wouter2203/fuzzy-search/issues/32"}}}

**Comment by wouter2203** [comment]
updated in https://github.com/wouter2203/fuzzy-search/commit/e3f1ceeeb87dbbd16c14fd9997b7812ae03183d2
